Due 1/27/17: 

-Find the electron quantum number (nx, ny, m) up to E_nx_ny = 10 hbar w

-Make a small program that sets this table, arbitrary cut in n hbar w (first do n = 10)

-Look up analytical form of psi_nx_ny(x,y)

-Set up table in paper and pencil then make program

In [5]:
import numpy as np
from sympy import hermite, diff
from sympy.abc import x, n
import scipy
from Vector import Vector as vec
import math
import scipy.linalg as la
from decimal import *

def magic(n):
    #given shell number n, returns magic number at n
    result = 0
    for i in range(1,n+1):
        result += 2*i
    return result

def energy(n):
    #given shell number n, returns energy at n
    result = 0
    for i in range(1,n+1):
        result += 2*i**2
    return result

def nx_ny(n):
    #given shell number n, returns tuple of possible quantum numbers in (nx, ny) form
    quantum_numbers = []
    for i in range(n+1):
        quantum_numbers.append(vec(i,n-i))
    return tuple(quantum_numbers)

def n_m(e):
    quantum_numbers = []
    for m in range(e-1,-e,-2):
        quantum_numbers.append(vec((e-abs(m)-1)//2,m))
    #for m in range(-e,e,2):
    #    quantum_numbers.append((()))
    #for m in range(e-1,-1,-2):
        #quantum_numbers.append(((e-abs(m)-1)//2,m))
        #quantum_numbers.append(((e-abs(m)-1)//2,-m))


    return tuple(quantum_numbers)

def wavefunction(n):
    #given shell number n, returns the hermite polynomial at that n
    return hermite(n,x)


class single_particle():

    def __init__(self, i, n, m, m_s, state):
        #takes in n, corresponding to shell number, where n = 1,2,3...
        self.shell = i
        self.n = n
        self.m = m
        self.degeneracy = 2*i
        self.E_nx_ny = str(i)
        self.magic_number = magic(i)
        self.energy = energy(i)
        self.nx_ny = []
        self.n_m = [n,m]
        self.state = state
        self.m_s = m_s
        self.wavefunction = wavefunction(i)
        self.l = abs(self.m)
        self.j = self.l + self.m_s
        #self.j_tot = math.sqrt(self.j*(self.j+1))
        
        if self.m_s < 0:
            self.spin_state = vec(0,1)
        elif self.m_s > 0:
            self.spin_state = vec(1,0)
#         if self.m_s > 0:
#             self.spin_state = vec(1,0)
#         elif self.m_s < 0:
#             self.spin_state = vec(0,1)

    def data_tuple(self):
        return (self.shell, self.degeneracy, self.E_nx_ny, self.magic_number, 
                self.energy, self.nx_ny, self.n_m, self.wavefunction)


In [6]:
#Fill the table

import pandas as pd

s_lst = [-0.5,0.5]
#attempt to generalize fill_arrays rather than hard code
def fill_arrays(n, quantities):
    count = 0

    for i in range(n-1):
        #create list of possible quantum numbers
        #i = quantum number arrays index
        nx_ny_lst = nx_ny(i)
        n_m_lst = n_m(i+1)
        n_m_lst = n_m_lst[::-1]
            

        for j in range(i+1):
            
            for s in s_lst:
                #create instance of particle, each with unique quantum numbers
                n = n_m_lst[j].x
                m = n_m_lst[j].y
                particle = single_particle(i+1,n,m,s,count)
                particle.nx_ny = nx_ny_lst[j]
                particle.n_m = n_m_lst[j]
                #particle.m_s = k
                #particle.state = count
                particles.append(particle)
                data = (particle.shell, particle.degeneracy, particle.E_nx_ny, particle.magic_number, 
                    particle.energy, particle.nx_ny, particle.n_m, particle.wavefunction)
                count += 1

                for l in range(len(quantities)-1):
                    #store quantities in different places;
                    #for data that have type int, such as energy, E_nx_ny, etc. I put them in arrays, inserted in the 'else' block
                    #for data with other types, such as quantum number (tuple), I put them in list, inserted in the 'if' block
                    if isinstance(quantities[l],list):
                        quantities[l].append(data[l])
                    else:
                        quantities[l][i] = data[l]


shells=3
data_dict = {}

shell_arr = np.empty(shells-1)
degeneracy_arr = np.empty(shells-1)
E_nx_ny_arr = np.empty(shells-1)
magic_number_arr = np.empty(shells-1)
energy_arr = np.empty(shells-1) 
nx_ny_arr = []
n_m_arr = []
wavefunction_arr = []
particles = []
quantities = [shell_arr, degeneracy_arr, E_nx_ny_arr, magic_number_arr, energy_arr, nx_ny_arr, n_m_arr, wavefunction_arr]
names = ("Shell", "Degeneracy", "E_nx_ny", "Magic Numbers", "Energy", "(nx, ny)", "(n, m)", "Wavefunctions")


fill_arrays(shells,quantities)





In [7]:
'''write to file'''

file_spnumbers = open('nucleispnumbers.dat', 'w')
file_twobody = open('nucleitwobody.dat', 'w')
#header = "|n>,n,m,2s,2m_s"
#header = "shell,n,l,j,m,m_s"
header = "|i>,(n,m), spin state,m_s"
#file.write(header)
#file.write("\n")
print(header)

for p in particles:
    #q_str = "|{}>, {}, {}, {}".format(p.state,p.n_m,1,2*p.m_s)
    s_str = "|{}>, ({},{}), {}, {}".format(p.state,p.n,p.m,p.spin_state, 2*p.m_s)
    #file.write(quantum_no_str)
    #file.write("\n")
    sp_str = "{},{},{},{},{}".format(p.state,p.n,p.m,1,int(2*p.m_s))
    file_spnumbers.write(sp_str)
    file_spnumbers.write("\n")
    for q in particles:
        two_body_str = "{},{},{},".format(p.state,q.state,p.spin_state.dot(q.spin_state))
        file_twobody.write(two_body_str)
        file_twobody.write("\n")
#         for r in particles:

#             for s in particles:
#                 H_0 = p.shell + q.shell + r.shell + s.shell
#                 H = H_0 + 0
#                 two_body_str = "{},{},{},{},{}".format(p.state,q.state,r.state,s.state,H)
#                 file_twobody.write(two_body_str)
#                 file_twobody.write("\n")
#     #print(q_str)
#     #print(quantum_no_str)
    print(s_str)
file_spnumbers.close()
file_twobody.close()

|i>,(n,m), spin state,m_s
|0>, (0,0), (0, 1), -1.0
|1>, (0,0), (1, 0), 1.0
|2>, (0,-1), (0, 1), -1.0
|3>, (0,-1), (1, 0), 1.0
|4>, (0,1), (0, 1), -1.0
|5>, (0,1), (1, 0), 1.0


In [11]:
def single_H(hbar_omega, shell):
    return hbar_omega*(shell+1)

states = []
n = []
m = []
m_s = []
non_zero_combinations = []
NParticles=6
max_iter = 100
epsilon = 10**(-4)


with open("nucleispnumbers.dat", "r") as qnumfile:
    for line in qnumfile:
        nums = line.split(",")
        states.append(nums[0])
        n.append(int(nums[1]))
        m.append(int(nums[2]))
        m_s.append(int(nums[4]))

spOrbitals = len(states)
two_interaction = np.zeros([spOrbitals,spOrbitals])

with open("nucleitwobody.dat", "r") as twobodyfile:
    for line in twobodyfile:
        nums = line.split(",")
        '''Matrix two_interaction has row, column indices for the first and second interacting electron respectively'''
        '''Value at those indices is the inner product of the two spin states'''
        two_interaction[int(nums[0])][int(nums[1])] = int(nums[2])
        #print(nums)
#header = "<a,b|c,d>/2"
#print(header)
hbar_omega = 1
CMatrix = np.eye(spOrbitals) # HF coefficients
DensityMatrix = np.zeros([spOrbitals,spOrbitals])
HFMatrix = np.zeros([spOrbitals,spOrbitals])


#print("Original Density Matrix \n {}".format(DensityMatrix))
singleparticleH = np.zeros(spOrbitals)
hf_count = 0
maxHFiter = 100
difference = 1
epsilon = 10**-3
for i in range(spOrbitals):
    singleparticleH[i] = Decimal(single_H(hbar_omega,i))
while hf_count < maxHFiter:
    for alpha in range(len(particles)):
        a = particles[alpha]

        for beta in range(len(particles)):
            b = particles[beta]
            M_s_ab = m_s[alpha] + m_s[beta]
            M_ab = m[alpha] + m[beta]
            '''Add initial term for E_a_b'''
            if beta == alpha:   
                HFMatrix[alpha][beta] = singleparticleH[alpha]
                spenergies, CMatrix = np.linalg.eigh(HFMatrix)
            DensityMatrix = np.zeros([spOrbitals,spOrbitals])

            for gamma in range(len(particles)):
                c = particles[gamma]

                for delta in range(len(particles)):
                    d = particles[delta]
                    M_s_cd = m_s[gamma] + m_s[delta]
                    M_cd = m[gamma] + m_s[delta]
                    C_sum = 0
                    direct_exchange_term = 0.0
                    
                    '''Test for spin and M conservation'''
                    if M_s_ab == M_s_cd and M_ab == M_cd:
                        direct = two_interaction[alpha][gamma] + two_interaction[beta][delta]
                        exchange = two_interaction[alpha][delta] + two_interaction[beta][gamma]
                        direct_exchange_term = (direct + exchange)/2


                    '''Summing C terms'''
                    for j in range(NParticles):
                        C_sum += CMatrix[gamma][j]*CMatrix[delta][j]
                    
                    '''Update Density and HF Matrix'''
                    DensityMatrix[gamma][delta] = Decimal(C_sum)# + Decimal(direct_exchange_term)
                    HFMatrix[alpha][beta] += C_sum*direct_exchange_term
                    



                        #print("<{},{}|{},{}> = ({}*{})*({}*{}) = {}".format(a,b,c,d,a.spin_state, c.spin_state, b.spin_state, 
                        #                                                   d.spin_state, a.spin_state.dot(c.spin_state)*b.spin_state.dot(d.spin_state)))
            #HFmatrix[alpha][beta] = Decimal(sumFockTerm)
    hf_count += 1
print("Final Hartree Fock Matrix \n {}".format(HFMatrix))
print("Final C Matrix \n {}".format(CMatrix))
#print("Final Density Matrix \n {}".format(DensityMatrix))
print("SP energies \n {}".format(spenergies))


Final Hartree Fock Matrix 
 [[  3.00000000e+00  -9.64134700e-18   2.00000000e+02  -2.56075767e-16
    0.00000000e+00  -2.55251787e-17]
 [ -9.64134700e-18   4.00000000e+00  -1.91217851e-16   0.00000000e+00
   -1.07449605e-16   2.00000000e+02]
 [  2.00000000e+02  -1.91217851e-16   5.00000000e+00  -4.58968497e-16
    2.00000000e+02  -3.31840163e-16]
 [  6.39891490e-18   0.00000000e+00  -4.58968497e-16   4.00000000e+00
    9.50244798e-17   2.00000000e+02]
 [  0.00000000e+00   9.69701817e-17   2.00000000e+02   9.50244798e-17
    5.00000000e+00  -4.40212387e-16]
 [ -2.61071485e-17   2.00000000e+02  -4.40261217e-16   2.00000000e+02
   -4.40212387e-16   8.00000000e+00]]
Final C Matrix 
 [[ -5.02214186e-01   0.00000000e+00   0.00000000e+00   7.07093523e-01
   -4.97794798e-01   0.00000000e+00]
 [  0.00000000e+00  -5.00883098e-01   7.07106781e-01   0.00000000e+00
    0.00000000e+00  -4.99115339e-01]
 [  7.06477071e-01   0.00000000e+00   0.00000000e+00   3.53551181e-03
   -7.07727100e-01   0.00000

In [27]:
'''Testing access to two_body matrix'''
with open("nucleitwobody.dat", "r") as twobodyfile:
    for line in twobodyfile:
        nums = line.split(",")
        two_interaction[int(nums[0])][int(nums[1])] = int(nums[2])
        
        
for alpha in range(len(particles)):
        for beta in range(len(particles)):
            a = particles[alpha]
            b = particles[beta]
            M_s_ab = a.m_s + b.m_s
            M_ab = a.m + b.m
            '''Add initial term for E_a_b'''
            if beta == alpha:   
                HFMatrix[alpha][alpha] += singleparticleH[alpha]
                spenergies, CMatrix = np.linalg.eigh(HFMatrix)
            #print("<{}|{}> = {}*{} = {}".format(a.state,b.state, a.spin_state, b.spin_state, a.spin_state.dot(b.spin_state)))
            for gamma in range(len(particles)):
                c = particles[gamma]

                for delta in range(len(particles)):
                    d = particles[gamma]

print(two_interaction)

[[[[ 0.  0.]
   [ 0.  0.]]

  [[ 0.  0.]
   [ 0.  0.]]]


 [[[ 0.  0.]
   [ 0.  0.]]

  [[ 0.  0.]
   [ 0.  0.]]]]


In [11]:
sum_ = 0.0
for i in range(Nparticles):
    sum_ += C[gamma][i]*C[delta][i]
    print("gamma: {} i: {} delta: {}".format(gamma,i,delta))
DensityMatrix[gamma][delta] = Decimal(sum_)

NameError: name 'Nparticles' is not defined

In [ ]:
# #Fill the table
# Old Code
# import pandas as pd

# def fill_arrays(n):
#     for i in range(n-1):
#         nx_ny_lst = nx_ny(i)
#         n_m_lst = n_m(i+1)
#         print(nx_ny_lst)
#         print(n_m_lst)
#         for j in range(i+1):
#             particle = single_particle(i+1)
#             particle.nx_ny = nx_ny_lst[j]
#             particle.n_m = n_m_lst[j]

#             particles.append(particle)
#             data = particle.data_tuple()
#             shell_arr[i] = data[0]
#             degeneracy_arr[i] = data[1]
#             E_nx_ny_arr[i] = data[2]
#             magic_number_arr[i] = data[3]
#             energy_arr[i] = data[4]
#             nx_ny_arr.append(data[5])
#             n_m_arr.append(data[6])
#             wavefunction_arr.append(data[7])

# #attempt to generalize fill_arrays rather than hard code
# def fill_arrays_2(n, quantities):
#     for i in range(1,n):
#         particle = single_particle(i)
#         particles.append(particle)
#         data = (particle.shell, particle.degeneracy, particle.E_nx_ny, particle.magic_number, 
#                 particle.energy, particle.nx_ny, particle.n_m, particle.wavefunction)
        
#         for j in range(len(quantities)-1):
#             print(quantities[j],quantities[j][i-1],data[j])
#             if type(quantities) == 'list':
#                 quantities[j].append(data[j])
#             else:
#                 quantities[j][i-1] = data[j]

# n=10
# data_dict = {}

# shell_arr = np.empty(n-1)
# degeneracy_arr = np.zeros(n-1)
# E_nx_ny_arr = np.zeros(n-1)
# magic_number_arr = np.zeros(n-1)
# energy_arr = np.zeros(n-1) 
# nx_ny_arr = []
# n_m_arr = []
# wavefunction_arr = []
# particles = []
# quantities = [shell_arr, degeneracy_arr, E_nx_ny_arr, magic_number_arr, energy_arr, nx_ny_arr, n_m_arr, wavefunction_arr]
# names = ("Shell", "Degeneracy", "E_nx_ny", "Magic Numbers", "Energy", "(nx, ny)", "(n, m)", "Wavefunctions")

# fill_arrays(n)

# #fill_arrays_2(n,quantities)

# for i in range(len(names)):
#     data_dict[names[i]] = quantities[i]
# pd.DataFrame(data_dict)
